### PR TITLE
Added draft preview feature

### PR DESCRIPTION
**Pull request by rsm0128**
image

- Made `preview` button for draft post work

### CODE REVIEW

**Comment by rsm0128** [comment]
Work with https://github.com/funkhaus/see-me-frontend/pull/10

**Comment by drewbaker** [comment]
I’m curious why this is needed? 

If the frontend sends valid cookies, shouldn’t Wordpress just return the data? Why do we need to send custom parameters?

**Comment by rsm0128** [comment]
@drewbaker The API request is sent from Nuxt server and it doesn't have the user Cookies.

**Comment by drewbaker** [comment]
When is it sent by Nuxt server? If so, then that is wrong. When ?preview is in the URL, Nuxt should run requests from client side.

https://nuxt.com/docs/api/composables/use-preview-mode

**Pull request closed without merging**
